apiVersion: apps/v1   # Kubernetes API for Deployment
kind: Deployment      # We are creating a Deployment (manages pods)

metadata:
  name: devops-app    # Name of your app (you can keep this same)

  labels:
    app: devops-app   # Label used to identify your app

spec:
  replicas: 2         # Number of pods (2 copies of your app running)

  selector:
    matchLabels:
      app: devops-app   # Must match below template labels (VERY IMPORTANT)

  template:
    metadata:
      labels:
        app: devops-app   # Pod label (must match selector above)

    spec:
      containers:
      - name: devops-container   # Container name (any name is fine)

        image: praj83/devops-app:latest  
        # 👆 IMPORTANT:
        # This is your Docker image
        # Format: <docker-username>/<image-name>:<tag>
        # You can keep 'latest' for now (we will automate later)

        ports:
        - containerPort: 3000
        # 👆 Your app is running on port 3000 inside container
