apiVersion: v1
kind: Service   # Service exposes your app to outside world

metadata:
  name: devops-service   # Name of service (can keep same)

spec:
  type: LoadBalancer
  # 👆 IMPORTANT:
  # AWS will create a Load Balancer automatically
  # This gives you PUBLIC URL

  selector:
    app: devops-app
    # 👆 Must match deployment label (VERY IMPORTANT)

  ports:
    - protocol: TCP
      port: 80
      # 👆 Public port (users access this)

      targetPort: 3000
      # 👆 Container port (your app runs here)
