name: Deploy to EKS

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      # Install kubectl (clean way)
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Configure AWS (BEST PRACTICE)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Debug (VERY IMPORTANT)
      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      # Connect to EKS
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ap-south-1 --name devops-cluster

      # Deploy app
      - name: Deploy to EKS
        run: kubectl apply -f .
